# Generated by Django 4.2.2 on 2023-06-16 16:14

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "img",
                    models.ImageField(
                        blank=True, null=True, upload_to=posts.models.upload_post_path
                    ),
                ),
            ],
        ),
    ]
