# Generated by Django 4.2.2 on 2023-06-17 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="liked",
            field=models.ManyToManyField(
                blank=True, related_name="liked", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="userPost",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userPost",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
